# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Alex Zervopoulos
title: Informatics Undergraduate Student
email: alex.zervopoulos@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
# github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile_pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey, I'm Alex and I'm currently an undergraduate student on my fourth year at the Department of Informatics of the Ionian University. In these 4 years, I've developed a diverse set of skills revolving around Computer Science, as well as technology in general. I've worked on a variety of projects, ranging from wireless sensor networks all the way to 3D games. Overall, I'm highly passionate about the field, as I deeply enjoy its problem solving nature.

  I am most skilled in: <mark>Python</mark> and <mark>C</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my other interests and hobbies include:
   - Gaming
   - Science
   - Music
   - Psychology

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
